"""Document generation: PDD, SDD, and the modernization report.

Implemented in roadmap week 5. Markdown is the primary output; DOCX is
produced via pandoc when it is installed, and skipped with an honest
notice when it is not. Every generator that consumes a spec passes
through the review gate before doing anything else; the gate call is
the first line, not a decoration.

Generation is a pure mapping from the artifacts to a document, no LLM
involved: every statement in a generated document traces to the estate
model, the approved spec, or the uplift report. Where a document needs
something the source cannot provide (selectors, credentials, agentic
design decisions), it says so in an explicit TODO instead of guessing.
"""

import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

from bp2uip.analysis import build_dependency_graph, config_constants, score_complexity
from bp2uip.gate import require_approved
from bp2uip.model import (
    ComplexityScore,
    Estate,
    IntentSpec,
    Process,
    ProcessDependencies,
    Stage,
    UpliftReport,
)
from bp2uip.provenance import ProvenanceLog
from bp2uip.render import _cites, _stage_index

ACTOR = "bp2uip/docsgen"


@dataclass
class GeneratedDoc:
    markdown_path: Path
    docx_path: Path | None = None


class GenerationError(Exception):
    """The inputs do not line up (missing process, mismatched spec)."""


def _find_process(estate: Estate, process_id: str) -> Process:
    process = next((p for p in estate.processes if p.id == process_id), None)
    if process is None:
        raise GenerationError(f"process {process_id} is not in the estate")
    return process


def _try_docx(markdown_path: Path) -> Path | None:
    """Convert the markdown to DOCX when pandoc is available. Returns
    the DOCX path, or None (honestly, not a fake) when it is not."""
    if shutil.which("pandoc") is None:
        return None
    docx_path = markdown_path.with_suffix(".docx")
    subprocess.run(
        ["pandoc", str(markdown_path), "-o", str(docx_path)],
        check=True,
        capture_output=True,
    )
    return docx_path


def _write(out_dir: Path, name: str, content: str) -> GeneratedDoc:
    out_dir.mkdir(parents=True, exist_ok=True)
    markdown_path = out_dir / name
    markdown_path.write_text(content, encoding="utf-8")
    return GeneratedDoc(markdown_path=markdown_path, docx_path=_try_docx(markdown_path))


def _record_generation(log: ProvenanceLog, kind: str, spec: IntentSpec, doc: GeneratedDoc) -> None:
    log.append(
        actor=ACTOR,
        event="generation",
        detail={"kind": kind, "spec_id": spec.spec_id, "path": str(doc.markdown_path)},
    )


# --------------------------------------------------------------------------
# Shared building blocks
# --------------------------------------------------------------------------


def _provenance_header(spec: IntentSpec, extra: list[str] | None = None) -> list[str]:
    lines = [
        "Generated by BP2UIP; do not edit by hand. Every statement in this",
        "document derives from the parsed source, the reviewed intent spec,",
        "or the uplift analysis, and the provenance log next to it records",
        "how it was produced.",
        "",
        f"- Spec: `{spec.spec_id}` (**{spec.status}**)",
    ]
    if spec.approval is not None:
        lines.append(
            f"- Approved by: **{spec.approval.approved_by}** at {spec.approval.approved_at}"
        )
    else:
        lines.append("- Approval: none; this document was force-generated from a draft")
    lines += [
        f"- Extracted by: {spec.extraction.provider}/{spec.extraction.model} "
        f"(prompt v{spec.extraction.prompt_version})",
        f"- Source estate: `{spec.estate_ref.path}` (sha256 `{spec.estate_ref.sha256[:12]}...`)",
    ]
    lines += extra or []
    return lines


def _stage_detail(stage: Stage) -> str:
    props = stage.properties
    if stage.type == "decision":
        return f"`{props.get('expression', '')}`"
    if stage.type in ("action",):
        return f"{props.get('object', '?')} :: {props.get('action', '?')}"
    if stage.type in ("queue_read", "queue_write"):
        queue = props.get("queue_name")
        action = props.get("action", "")
        return f"{action}" + (f" on {queue}" if queue else " (current item)")
    if stage.type == "calculation":
        expression = props.get("expression")
        if expression:
            return f"`{expression}`"
        steps = props.get("steps") or []
        return f"{len(steps)} assignment(s)" if steps else ""
    if stage.type == "exception":
        return f"{props.get('exception_type', 'exception')}: {props.get('detail', '')}"
    if stage.type == "loop_start":
        return f"for each row in `{props.get('collection', '?')}`"
    if stage.type == "subprocess_call":
        return str(props.get("process", ""))
    return ""


def _flow_walk(process: Process) -> list[tuple[Stage, str]]:
    """Stages in depth-first link order from the start stage, true
    branches first, each paired with a branch annotation. Stages not
    reachable from start (recovery chains) follow, marked as such."""
    stages = {s.id: s for s in process.stages}
    outgoing: dict[str, list[tuple[str | None, str]]] = {}
    for link in process.links:
        outgoing.setdefault(link.from_stage, []).append((link.label, link.to_stage))
    for targets in outgoing.values():
        # true before false before unlabeled order is stable for reading
        targets.sort(key=lambda t: {"true": 0, "false": 1}.get(t[0] or "", 2))

    ordered: list[tuple[Stage, str]] = []
    visited: set[str] = set()

    def visit(stage_id: str, annotation: str) -> None:
        if stage_id in visited or stage_id not in stages:
            return
        visited.add(stage_id)
        ordered.append((stages[stage_id], annotation))
        for label, target in outgoing.get(stage_id, []):
            branch = f"on {label} from '{stages[stage_id].name}'" if label else ""
            visit(target, branch)

    for stage in process.stages:
        if stage.type == "start":
            visit(stage.id, "")
    for stage in process.stages:
        if stage.id not in visited:
            visit(stage.id, "exception recovery path")
    return ordered


# --------------------------------------------------------------------------
# PDD: the as-is process document
# --------------------------------------------------------------------------


def generate_pdd(
    estate: Estate,
    spec: IntentSpec,
    log: ProvenanceLog,
    *,
    out_dir: Path,
    force: bool = False,
) -> GeneratedDoc:
    """As-is process document from parser output plus approved intent."""
    require_approved(spec, log, force=force, actor=ACTOR)
    process = _find_process(estate, spec.process_id)
    index = _stage_index(estate)
    deps = next(d for d in build_dependency_graph(estate).processes if d.process_id == process.id)
    queues_by_name = {q.name: q for q in estate.queues}

    lines = [f"# Process Definition Document (as-is): {process.name}", ""]
    lines += _provenance_header(spec)

    lines += ["", "## 1. Purpose", "", spec.purpose.text, ""]
    lines.append(f"Evidence: {_cites(spec.purpose.citations, index)}")

    lines += ["", "## 2. Trigger and workload", ""]
    reads = [s for s in process.stages if s.type == "queue_read"]
    start_inputs = next(
        (s.properties.get("inputs") or [] for s in process.stages if s.type == "start"), []
    )
    if reads:
        for stage in reads:
            queue_name = str(stage.properties.get("queue_name", ""))
            queue = queues_by_name.get(queue_name)
            detail = (
                f" (key field {queue.key_field}, max {queue.max_attempts} attempts)"
                if queue is not None
                else ""
            )
            lines.append(
                f"- Transactional: works items from queue **{queue_name}**{detail}, "
                f"read at '{stage.name}'."
            )
    if start_inputs:
        params = ", ".join(f"{p.get('name')} ({p.get('type')})" for p in start_inputs)
        lines.append(f"- Invoked with parameters: {params}.")
    if not reads and not start_inputs:
        lines.append(
            "- No queue reads and no start parameters in the source; the "
            "trigger is external to the export (scheduler or manual run)."
        )

    lines += ["", "## 3. Inputs", ""]
    if spec.inputs:
        lines += ["| Input | Description | Source | Evidence |", "|---|---|---|---|"]
        lines += [
            f"| {i.name} | {i.description} | {i.source} | {_cites(i.citations, index)} |"
            for i in spec.inputs
        ]
    else:
        lines.append("None identified in the reviewed spec.")

    lines += ["", "## 4. Outputs", ""]
    if spec.outputs:
        lines += ["| Output | Description | Destination | Evidence |", "|---|---|---|---|"]
        lines += [
            f"| {o.name} | {o.description} | {o.destination} | {_cites(o.citations, index)} |"
            for o in spec.outputs
        ]
    else:
        lines.append("None identified in the reviewed spec.")

    lines += [
        "",
        "## 5. Current-state flow",
        "",
        "Stages in link order from Start, true branches first; stages",
        "reachable only through exception recovery follow at the end.",
        "",
        "| # | Stage | Type | Detail | Reached |",
        "|---|---|---|---|---|",
    ]
    for i, (stage, annotation) in enumerate(_flow_walk(process), start=1):
        lines.append(
            f"| {i} | {stage.name} | {stage.type} | {_stage_detail(stage)} | {annotation} |"
        )

    lines += ["", "## 6. Business rules", ""]
    if spec.business_rules:
        for rule in spec.business_rules:
            lines += [
                f"**{rule.id}.** {rule.statement}",
                "",
                f"Evidence: {_cites(rule.citations, index)}",
                "",
            ]
        lines.pop()
    else:
        lines.append("None identified in the reviewed spec.")

    lines += ["", "## 7. Current exception handling", ""]
    if spec.exception_semantics:
        lines += ["| When | Current handling | Evidence |", "|---|---|---|"]
        lines += [
            f"| {s.condition} | {s.current_handling} | {_cites(s.citations, index)} |"
            for s in spec.exception_semantics
        ]
    else:
        lines.append("None identified in the reviewed spec.")
    for block in process.exception_blocks:
        handler = index.get(block.handler_stage, block.handler_stage)
        lines += [
            "",
            f"Structural: an exception block covers {len(block.covers_stages)} "
            f"stage(s); exceptions inside it are handled at {handler}.",
        ]

    lines += ["", "## 8. Systems and dependencies", ""]
    if deps.objects:
        for use in deps.objects:
            lines.append(f"- **{use.object}**: {', '.join(use.actions)}")
    if deps.queues:
        for queue_use in deps.queues:
            lines.append(
                f"- Queue **{queue_use.queue}**: {queue_use.reads} read(s), "
                f"{queue_use.adds} add(s), {queue_use.dispositions} disposition(s)"
            )
    if deps.subprocesses:
        for sub in deps.subprocesses:
            lines.append(f"- Subprocess: {sub}")
    if not (deps.objects or deps.queues or deps.subprocesses):
        lines.append("No object, queue, or subprocess dependencies in the source.")

    lines += ["", "## 9. Human touchpoints", ""]
    if spec.human_touchpoints:
        for touchpoint in spec.human_touchpoints:
            lines += [
                f"- {touchpoint.description}",
                f"  Evidence: {_cites(touchpoint.citations, index)}",
            ]
    else:
        lines.append("None identified in the reviewed spec.")

    constants = sorted(config_constants(process))
    values = {d.name: d.initial_value for d in process.data_items}
    lines += ["", "## 10. Configuration", ""]
    if constants:
        lines += ["| Setting | Current value |", "|---|---|"]
        lines += [f"| {name} | {values.get(name)} |" for name in constants]
        lines += [
            "",
            "Configuration means a data item with an initial value that no",
            "stage writes; values shown are the current values in the source.",
        ]
    else:
        lines.append("No configuration constants in the source.")

    lines.append("")
    doc = _write(out_dir, "pdd.md", "\n".join(lines))
    _record_generation(log, "pdd", spec, doc)
    return doc


# --------------------------------------------------------------------------
# SDD: the to-be design document
# --------------------------------------------------------------------------


def _target_architecture(deps: ProcessDependencies, couplings: list, process: Process) -> list[str]:
    reads = [q for q in deps.queues if q.reads]
    adds = [q for q in deps.queues if q.adds]
    lines: list[str] = []
    if reads:
        names = ", ".join(q.queue for q in reads)
        lines.append(
            f"- **REFramework transactional process (performer)**: the process "
            f"works items from {names}, which maps directly to the REFramework "
            f"transaction loop over an Orchestrator queue."
        )
    if adds:
        names = ", ".join(q.queue for q in adds)
        lines.append(
            f"- **Dispatcher**: the process adds items to {names}; in UiPath "
            f"this becomes a dispatcher feeding the Orchestrator queue."
        )
    if not reads and not adds:
        lines.append(
            "- **Sequential workflow**: no queue interaction in the source; a "
            "linear workflow (REFramework optional) invoked with arguments is "
            "the closest idiomatic shape."
        )
    for coupling in couplings:
        if process.id in coupling.producers:
            lines.append(
                f"- Forms a dispatcher/performer pair through **{coupling.queue}**; "
                f"migrate both sides in the same wave."
            )
        elif process.id in coupling.consumers and coupling.producers:
            lines.append(
                f"- Consumes **{coupling.queue}**, which another process in the "
                f"estate feeds; migrate both sides in the same wave."
            )
    return lines


def generate_sdd(
    estate: Estate,
    spec: IntentSpec,
    uplift: UpliftReport,
    log: ProvenanceLog,
    *,
    out_dir: Path,
    force: bool = False,
) -> GeneratedDoc:
    """To-be design document from approved intent plus the uplift analysis."""
    require_approved(spec, log, force=force, actor=ACTOR)
    process = _find_process(estate, spec.process_id)
    if uplift.process_id != process.id:
        raise GenerationError(
            f"uplift report is for process {uplift.process_id}, spec is for {process.id}"
        )
    index = _stage_index(estate)
    graph = build_dependency_graph(estate)
    deps = next(d for d in graph.processes if d.process_id == process.id)
    queues_by_name = {q.name: q for q in estate.queues}
    constants = sorted(config_constants(process))
    values = {d.name: d.initial_value for d in process.data_items}

    lines = [f"# Solution Design Document (to-be): {process.name}", ""]
    lines += _provenance_header(
        spec,
        extra=[
            f"- Uplift analysis: criteria v{uplift.criteria_version}, "
            f"analyzed {uplift.analyzed_at} "
            f"(spec **{uplift.spec_ref.status_at_analysis}** at analysis time)",
        ],
    )

    lines += ["", "## 1. Target architecture", ""]
    lines += _target_architecture(deps, graph.queue_couplings, process)

    lines += ["", "## 2. Queue and configuration design", ""]
    if deps.queues:
        lines += [
            "| Blue Prism queue | UiPath design | Key field | Retries |",
            "|---|---|---|---|",
        ]
        for queue_use in deps.queues:
            queue = queues_by_name.get(queue_use.queue)
            lines.append(
                f"| {queue_use.queue} | Orchestrator queue | "
                f"{queue.key_field if queue else '?'} | "
                f"{queue.max_attempts if queue else '?'} |"
            )
        lines.append("")
    if constants:
        lines += [
            "| Setting | Value to carry over | UiPath home |",
            "|---|---|---|",
        ]
        lines += [
            f"| {name} | {values.get(name)} | Config.xlsx / Orchestrator asset |"
            for name in constants
        ]
    if not deps.queues and not constants:
        lines.append("No queues and no configuration constants to design for.")

    lines += ["", "## 3. Exception taxonomy mapping", ""]
    rows: list[str] = []
    for stage in process.stages:
        exc_type = str(stage.properties.get("exception_type", ""))
        if stage.type == "exception" and "business" in exc_type.lower():
            rows.append(
                f"| Throw at '{stage.name}' | Business Exception | "
                f"`BusinessRuleException`: no retry, route to human follow-up |"
            )
        elif stage.type == "exception":
            rows.append(
                f"| Throw at '{stage.name}' | {exc_type or 'System Exception'} | "
                f"System exception: REFramework retry applies |"
            )
        elif (
            stage.type == "queue_write"
            and "exception" in str(stage.properties.get("action", "")).lower()
        ):
            rows.append(
                f"| '{stage.name}' | Queue item exception | "
                f"Set transaction status Failed (BusinessRuleException), no retry |"
            )
        elif stage.type == "recover":
            rows.append(
                f"| Recover at '{stage.name}' | Recovery block | "
                f"REFramework system-exception retry |"
            )
    if rows:
        lines += ["| Source construct | Blue Prism semantics | UiPath mapping |", "|---|---|---|"]
        lines += rows
    else:
        lines.append("No exception constructs in the source.")

    lines += [
        "",
        "## 4. Per-step decisions (from the uplift analysis)",
        "",
        "Classifications per docs/uplift-criteria.md; candidates are design",
        "inputs for the review below, not decisions already taken.",
        "",
        "| Finding | Classification | Stages | Criteria |",
        "|---|---|---|---|",
    ]
    for finding in uplift.findings:
        lines.append(
            f"| {finding.id} | {finding.classification} | "
            f"{_cites(finding.stage_ids, index)} | {', '.join(finding.criteria)} |"
        )
    candidates = [f for f in uplift.findings if f.classification == "AGENTIC_CANDIDATE"]
    for finding in candidates:
        lines += ["", f"**{finding.id}.** {finding.reasoning}"]

    lines += ["", "## 5. Human build TODO list", ""]
    todo = 1
    for use in deps.objects:
        lines.append(
            f"{todo}. Application interface for **{use.object}** "
            f"({', '.join(use.actions)}): selectors and screen automation are "
            f"not in the release export; build and test the UiPath library "
            f"actions against the real application."
        )
        todo += 1
    for finding in candidates:
        lines.append(
            f"{todo}. Decide finding **{finding.id}** ({', '.join(finding.criteria)}): "
            f"adopt the agentic design with a deterministic fallback, or keep "
            f"the current logic. Record the decision and its reasoning."
        )
        todo += 1
    lines.append(
        f"{todo}. Credentials, robot accounts, and schedules: not present in "
        f"the export; configure in Orchestrator."
    )

    lines += ["", "## 6. Provenance references", ""]
    lines += [
        f"- Intent spec: `{spec.spec_id}`, this directory's `intent-spec.json`",
        f"- Uplift report: this directory's `uplift.json` (criteria v{uplift.criteria_version})",
        f"- Source estate: `{spec.estate_ref.path}` (sha256 `{spec.estate_ref.sha256[:12]}...`)",
        "- Event log: this directory's `provenance.jsonl` (append-only, hash-chained)",
    ]

    lines.append("")
    doc = _write(out_dir, "sdd.md", "\n".join(lines))
    _record_generation(log, "sdd", spec, doc)
    return doc


# --------------------------------------------------------------------------
# Modernization report (estate-wide)
# --------------------------------------------------------------------------


def _wave(score: ComplexityScore, coupled_ids: set[str], waves: dict[str, int]) -> int:
    base = {"low": 1, "medium": 2, "high": 3}[score.band]
    coupled_waves = [waves[pid] for pid in coupled_ids if pid in waves]
    return max([base, *coupled_waves])


def generate_report(
    estate: Estate,
    specs: list[IntentSpec],
    uplift_reports: list[UpliftReport],
    *,
    out_dir: Path,
) -> GeneratedDoc:
    """Estate-wide modernization report: complexity, uplift findings, and
    a migration recommendation per process. Summarizes draft specs as
    drafts; it does not pass the gate because it generates nothing from
    spec content beyond its status."""
    scores = {s.process_id: s for s in score_complexity(estate)}
    graph = build_dependency_graph(estate)
    specs_by_id = {s.process_id: s for s in specs}
    uplift_by_id = {u.process_id: u for u in uplift_reports}

    # Coupled processes migrate together, in the later of their waves.
    coupled: dict[str, set[str]] = {p.id: set() for p in estate.processes}
    for coupling in graph.queue_couplings:
        members = set(coupling.producers) | set(coupling.consumers)
        for member in members:
            if member in coupled:
                coupled[member] |= members - {member}
    waves: dict[str, int] = {}
    for process in sorted(estate.processes, key=lambda p: scores[p.id].score):
        waves[process.id] = _wave(scores[process.id], coupled[process.id], waves)
    for process in estate.processes:  # settle pairs discovered later
        waves[process.id] = _wave(scores[process.id], coupled[process.id], waves)

    lines = [
        "# Modernization report",
        "",
        "Generated by BP2UIP from the estate model, the intent specs, and",
        "the uplift analysis; no LLM involved. Complexity is an ordinal",
        "ranking with documented weights, not an effort estimate. Waves are",
        "a suggested order: lower complexity first, queue-coupled processes",
        "held together in the later of their waves.",
        "",
        f"Estate: {len(estate.processes)} processes, {len(estate.objects)} objects, "
        f"{len(estate.queues)} queues (source parsed {estate.source.parsed_at}).",
        "",
        "| Process | Complexity | Spec | Agentic candidates | Suggested wave |",
        "|---|---|---|---|---|",
    ]
    for process in sorted(estate.processes, key=lambda p: (waves[p.id], scores[p.id].score)):
        score = scores[process.id]
        spec = specs_by_id.get(process.id)
        uplift = uplift_by_id.get(process.id)
        candidates = (
            sum(1 for f in uplift.findings if f.classification == "AGENTIC_CANDIDATE")
            if uplift
            else None
        )
        lines.append(
            f"| {process.name} | {score.score} ({score.band}) | "
            f"{spec.status if spec else 'none'} | "
            f"{candidates if candidates is not None else 'not analyzed'} | "
            f"{waves[process.id]} |"
        )

    for process in sorted(estate.processes, key=lambda p: (waves[p.id], scores[p.id].score)):
        score = scores[process.id]
        spec = specs_by_id.get(process.id)
        uplift = uplift_by_id.get(process.id)
        lines += ["", f"## {process.name}", ""]
        lines.append(
            f"Complexity {score.score} ({score.band}): {score.logic_stage_count} logic "
            f"stages, {score.decision_count} decisions, branching depth "
            f"{score.branching_depth}, {score.exception_construct_count} exception "
            f"construct(s)."
        )
        if spec is None:
            lines.append(
                "No intent spec; extract and review one before generating "
                "documents for this process."
            )
            continue
        if spec.status != "approved":
            lines.append(
                "Spec is a draft awaiting review; PDD/SDD generation will "
                "refuse to run until it is approved."
            )
        if uplift is None:
            lines.append("No uplift analysis; run `bp2uip analyze`.")
            continue
        gates = sum(1 for f in uplift.findings if f.classification == "HUMAN_GATE")
        candidates = [f for f in uplift.findings if f.classification == "AGENTIC_CANDIDATE"]
        lines.append(
            f"Uplift: {len(candidates)} agentic candidate(s), {gates} human "
            f"gate(s) to preserve, remainder deterministic."
        )
        for finding in candidates:
            lines.append(f"- {finding.id} ({', '.join(finding.criteria)}): {finding.reasoning}")
        partners = coupled[process.id]
        if partners:
            names = ", ".join(p.name for p in estate.processes if p.id in partners)
            lines.append(
                f"Recommendation: migrate in wave {waves[process.id]}, together "
                f"with {names} (queue-coupled)."
            )
        else:
            lines.append(f"Recommendation: migrate in wave {waves[process.id]}.")

    lines.append("")
    return _write(out_dir, "modernization-report.md", "\n".join(lines))
