"""Deterministic markdown rendering of artifacts.

The JSON artifact is canonical; the markdown written next to it is a
derived view so a spec can be read on GitHub or in a code review
without decoding GUIDs. Rendering is a pure mapping, no LLM involved,
and regenerating it never changes the underlying spec.
"""

from bp2uip.model import Estate, IntentSpec


def _stage_index(estate: Estate) -> dict[str, str]:
    """Map every stage id in the estate to a human-readable label."""
    index: dict[str, str] = {}
    for process in estate.processes:
        for stage in process.stages:
            index[stage.id] = f"{stage.name} ({stage.type})"
    for obj in estate.objects:
        for action in obj.actions:
            for stage in action.stages:
                index[stage.id] = f"{obj.name} / {action.name}: {stage.name} ({stage.type})"
    return index


def _cites(citations: list[str], index: dict[str, str]) -> str:
    # An id missing from the index renders verbatim rather than being
    # hidden; a reviewer should see exactly what the spec cites.
    return "; ".join(index.get(cited, cited) for cited in citations)


def spec_to_markdown(spec: IntentSpec, estate: Estate | None = None) -> str:
    """Render an intent spec as markdown, resolving citations to stage
    names when the estate is available (raw ids otherwise)."""
    index = _stage_index(estate) if estate is not None else {}
    process_name = spec.process_id
    if estate is not None:
        for process in estate.processes:
            if process.id == spec.process_id:
                process_name = process.name
                break

    lines: list[str] = [
        f"# Intent spec: {process_name}",
        "",
        "Derived view of `intent-spec.json` in this directory; the JSON is",
        "canonical. Regenerated by the pipeline, do not edit by hand.",
        "",
        f"- Status: **{spec.status}**",
        f"- Spec id: `{spec.spec_id}`",
        f"- Extracted by: {spec.extraction.provider}/{spec.extraction.model} "
        f"(prompt v{spec.extraction.prompt_version})",
        f"- Source estate: `{spec.estate_ref.path}` (sha256 `{spec.estate_ref.sha256[:12]}...`)",
        f"- Created: {spec.created_at}",
    ]
    if spec.approval is not None:
        lines.append(
            f"- Approved by: **{spec.approval.approved_by}** at {spec.approval.approved_at}"
        )
        if spec.approval.changes:
            lines.append(f"- Corrections at review: {len(spec.approval.changes)}")

    lines += [
        "",
        "## Purpose",
        "",
        spec.purpose.text,
        "",
        f"Evidence: {_cites(spec.purpose.citations, index)}",
        "",
        "## Inputs",
        "",
    ]
    if spec.inputs:
        lines += ["| Input | Description | Source | Evidence |", "|---|---|---|---|"]
        lines += [
            f"| {item.name} | {item.description} | {item.source} "
            f"| {_cites(item.citations, index)} |"
            for item in spec.inputs
        ]
    else:
        lines.append("None identified.")

    lines += ["", "## Outputs", ""]
    if spec.outputs:
        lines += ["| Output | Description | Destination | Evidence |", "|---|---|---|---|"]
        lines += [
            f"| {item.name} | {item.description} | {item.destination} "
            f"| {_cites(item.citations, index)} |"
            for item in spec.outputs
        ]
    else:
        lines.append("None identified.")

    lines += ["", "## Business rules", ""]
    if spec.business_rules:
        for rule in spec.business_rules:
            lines += [
                f"**{rule.id}.** {rule.statement}",
                "",
                f"Evidence: {_cites(rule.citations, index)}",
                "",
            ]
        lines.pop()  # drop the trailing blank line
    else:
        lines.append("None identified.")

    lines += ["", "## Exception semantics", ""]
    if spec.exception_semantics:
        lines += ["| When | Current handling | Evidence |", "|---|---|---|"]
        lines += [
            f"| {semantic.condition} | {semantic.current_handling} "
            f"| {_cites(semantic.citations, index)} |"
            for semantic in spec.exception_semantics
        ]
    else:
        lines.append("None identified.")

    lines += ["", "## Human touchpoints", ""]
    if spec.human_touchpoints:
        for touchpoint in spec.human_touchpoints:
            lines += [
                f"- {touchpoint.description}",
                f"  Evidence: {_cites(touchpoint.citations, index)}",
            ]
    else:
        lines.append("None identified.")

    lines.append("")
    return "\n".join(lines)
